---
title: "Lecture - Week 4 - Air Pollution Case Study"
author: "Ziq"
date: "March 24, 2019"
output: rmarkdown::github_document
---

So basically with this dataset is that it's to look at the dust in the air. There's been a clean air act and we want to see if today we have cleaner air.

We want a question. Basically are air quality levels lower?

```{r}
pm0 <- read.table("RD_501_88101_1999-0.txt", comment.char = "#", header = FALSE, sep = "|", na.strings = "")
cnames <- readLines("RD_501_88101_1999-0.txt", 1)
cnames <- strsplit(cnames, "|", fixed = TRUE)
names(pm0) <- cnames[[1]]

head(pm0)
names(pm0) <- make.names(cnames[[1]])
head(pm0)
```

```{r}
x0 <- pm0$Sample.Value
class(x0)
str(x0)
summary(x0)
mean(is.na(x0)) #14% are missing. Does the missing value matter? Let's compare it to pm1
```

```{r}
pm1 <- read.table("RD_501_88101_2012-0.txt", comment.char = "#", header = FALSE, sep = "|", na.strings = "")
dim(pm1)
names(pm1) <- make.names(cnames[[1]])
x1 <- pm1$Sample.Value
```
Let's compare x0 and dx1
```{r}
summary(x0)
summary(x1) #mean has decreased by half and median has decreased by half. But why are there negative values?
mean(is.na(x1)) #NA percentage has decreased with higher overall observations.
boxplot(x0, x1)
boxplot(log(x0),log(x1))
```

How many negatives are there?

```{r}
negative <- x1 < 0
sum(negative, na.rm = TRUE)
mean(negative, na.rm = TRUE)
dates <- pm1$Date
dates <- as.Date(as.character(dates), "%Y%m%d")
head(dates)
hist(dates, "month")
hist(dates[negative], 'month')
```

```{r}
site0 <- unique(subset(pm0, State.Code == 6, c(County.Code, Site.ID)))
site1 <- unique(subset(pm1, State.Code == 6, c(County.Code, Site.ID)))
head(site0)
site0 <- paste(site0[,1], site0[,2], sep = ".")
site1 <- paste(site1[,1], site1[,2], sep = ".")
str(site0)
str(site1)
both <- intersect(site0, site1)
pm0$county.site <- with(pm0, paste(County.Code, Site.ID, sep = "."))
pm1$county.site <- with(pm1, paste(County.Code, Site.ID, sep = "."))
cnt0 <- subset(pm0, State.Code == 6 & county.site %in% both)
cnt1 <- subset(pm1, State.Code == 6 & county.site %in% both)
head(cnt0)
sapply(split(cnt0, cnt0$county.site), nrow)
sapply(split(cnt1, cnt1$county.site), nrow)

```

```{r}
pm1sub <- subset(pm1, State.Code == 6)
pm0sub <- subset(pm0, State.Code == 6)
dates1 <- pm1sub$Date
x1sub <- pm1sub$Sample.Value
plot(dates1, x1sub)
dates1 <- as.Date(as.character(dates1), "%Y%m%d")
str(dates1)
plot(dates1, x1sub, ylim = c(0,400))
dates0 <- pm0sub$Date
dates0 <- as.Date(as.character(dates0), "%Y%m%d")
x0sub <- pm0sub$Sample.Value
plot(dates0, x0sub)
par(mfrow = c(1,2), mar = c(4,4,2,1))
plot(dates0, x0sub, pch = 20, alpha = 1/4)
abline(h = median(x0sub, na.rm=T))
plot(dates1, x1sub, pch = 20, ylim = c(0,140))
abline(h = median(x1sub, na.rm=T))
```

```{r}
mn0 <- with(pm0, tapply(Sample.Value, State.Code, mean, na.rm = TRUE))
str(mn0)
summary(mn0)
mn1 <- with(pm1, tapply(Sample.Value, State.Code, mean, na.rm = TRUE))
summary(mn1)
```

